### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Yashi30**

### CODE REVIEW

**Review by rgautam320 — COMMENTED** [review]
I don't know why are you want to make this change in this repository. Please write clearly.

**Comment by Yashi30** [comment]
I think readme is to be present in all projects to get the better understanding of what it is about , what is there in this without opening all individual files that's why i added this. sorry, if you found it invalid .You can remove this from your branch.

**Comment by rgautam320** [comment]
If you are trying to complete your Hactoberfest task then please contribute your code to this repository.

https://github.com/rgautam320/Hacktoberfest

**Comment by Yashi30** [comment]
Thanks!!

**Pull request merged**
